# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: faaba1579c6fec9545234ac4fd82476c12061e1af0b3bd39226beb8045619f38ee5002a71df8e2d3591e54d2c9caf3ce52974961481d61a27dc46525621258c8

test:
  secret_key_base: 944fdf8f28392a30ec7057b5c9bbb3f10b21d9209f7e55951ccbe4f22d2eda764691ac4dac80b6defe06bccf37aa6181b38f56c9a8754127d4e74b1ff5b5d520

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
